# Site settings
title: Space and Place Conference
email: mapref@mcmaster.ca
description: > # this means to ignore newlines until "baseurl:"
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "https://mcmaster-university-library.github.io/space-and-place" # the base hostname & protocol for your site
twitter_username:
github_username:

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
defaults:
  - scope:
      path: "assets/img"
    values:
      image: true

# Other options
excerpt_separator: "<!--more-->"

# SEO uff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""

exclude:
  - _site/
